// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oejcdpckxlkzdficzptx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lamNkcGNreGxremRmaWN6cHR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1NTg4NDAsImV4cCI6MjA1MjEzNDg0MH0.0IUFpOsJjY-pDmhqJyyNkJcczpEP4SNmwKok8OaQocQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);